apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ghvujyyv
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-ghvujyyv:6b63e1025c6920d9bca8069112d8632ab28e4413@sha256:589a2a9767879fd43871d1eab30aa8f8d6ee90b29cbca932c0938a15feeedb55
        name: container-image  
